### ISSUE TITLE
Application crash when Touch outside the dialog

### ISSUE THREAD

**Issue by vjsystematix** [Baseflow/XF-Material-Library#121]
Application is crashed when we touch outside the material dialog.

Is there any method to prevent the outside touch?

How to manage it, it would be great help to give some advice on it.

Note:- we have redirect navigation page on click of OK and touch outside. 

Device iOS 12.1

Thanks

**Comment by fabcall** [comment]
I noticed exactly the same when using ConfirmAsync, dunno about the other dialog methods.

**Comment by contrix09** [comment]
@vjsystematix what's stack trace of the exception?

**Comment by OdetteP** [comment]
Can you please showcase this in an PR by adding it to the MaterialMvvmSample in this repo?
If this is still an issue
