### ISSUE TITLE
Add Clear Entry icon 

### ISSUE THREAD

**Issue by muhammetsahin** [Baseflow/XF-Material-Library#123]
It would be nice if there was a clear entry.

![image](https://user-images.githubusercontent.com/2045788/54494796-3845e880-48ef-11e9-81b9-0713ec735ba1.png)

![image](https://user-images.githubusercontent.com/2045788/54494797-3bd96f80-48ef-11e9-8493-994a5f9d046a.png)

**Comment by fabcall** [comment]
For while, you can simple set an effect to add the Clear icon. I can drop a code here if you want.

**Comment by stephenhauck** [comment]
Please drop that code here if it;s not too much trouble ;)
THANKS!

**Comment by fabcall** [comment]
Here we go ;)

This is the platform effect.
```
using PlatformEffects = YOURNAMESPACE.Droid.Effects;
using RoutingEffects = YOURNAMESPACE.Shared.Effects;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using System.Linq;
using static YOURNAMESPACE.Droid.Resource;
using Android.Graphics;

[assembly: ResolutionGroupName("YOURNAMESPACE.Effects")]
[assembly: ExportEffect(typeof(PlatformEffects.MaterialTextFieldClearEntry), nameof(RoutingEffects.MaterialTextFieldClearEntry))]
namespace YOURNAMESPACE.Droid.Effects
{
    [Preserve(AllMembers = true)]
    public class MaterialTextFieldClearEntry : PlatformEffect
    {
        protected override void OnAttached()
        {
            ConfigureControl();
        }

        protected override void OnDetached()
        {
            var editText = Container.GetChildrenOfType<EditText>().FirstOrDefault();
            if (editText == null)
                return;

            editText?.SetOnTouchListener(null);
            editText.SetCompoundDrawablesRelativeWithIntrinsicBounds(0, 0, 0, 0);
        }

        void ConfigureControl()
        {
            var editText = Container.GetChildrenOfType<EditText>().FirstOrDefault();
            if (editText == null)
                return;

            editText.SetCompoundDrawablesRelativeWithIntrinsicBounds(0, 0, Xamarin.Toolkit.Effects.Resource.Drawable.fct_ic_clear_icon, 0);
            editText.SetOnTouchListener(new OnDrawableTouchListener());
            var clearIcon = editText.GetCompoundDrawablesRelative()[2];
            clearIcon.SetColorFilter(new PorterDuffColorFilter(Android.Graphics.Color.ParseColor("#4DFFFFFF"), PorterDuff.Mode.SrcIn));
        }
    }

    internal class OnDrawableTouchListener : Java.Lang.Object, global::Android.Views.View.IOnTouchListener
    {
        public bool OnTouch(global::Android.Views.View v, MotionEvent e)
        {
            if (v is EditText && e.Action == MotionEventActions.Up)
            {
                var editText = (EditText)v;
                if (e.RawX >= (editText.Right - editText.GetCompoundDrawables()[2].Bounds.Width()))
                {
                    editText.Text = string.Empty;
                    return true;
                }
            }

            return false;
        }
    }

    internal static class ViewGroupExtensions
    {
        internal static IEnumerable<T> GetChildrenOfType<T>(this AViewGroup self) where T : AView
        {
            for (var i = 0; i < self.ChildCount; i++)
            {
                AView child = self.GetChildAt(i);
                var typedChild = child as T;
                if (typedChild != null)
                    yield return typedChild;

                if (child is AViewGroup)
                {
                    IEnumerable<T> myChildren = (child as AViewGroup).GetChildrenOfType<T>();
                    foreach (T nextChild in myChildren)
                        yield return nextChild;
                }
            }
        }
    }
}
```
This is the shared effect:

```
using Xamarin.Forms;

namespace YOURNAMESPACE.Shared.Effects
{
    public class MaterialTextFieldClearEntry : RoutingEffect
    {
        public MaterialTextFieldClearEntry()
            : base("YOURNAMESPACE.Effects.MaterialTextFieldClearEntry")
        {
        }
    }
}
```
These are tested and working. Actually, they have been just adapted from XamarinCommunityToolkit. I can't do a solution for iOS, but you can adapt this:
```
using Foundation;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using PlatformEffects = YOURNAMESPACE.Effects.iOS;
using RoutingEffects = YOURNAMESPACE.Effects;

[assembly: ExportEffect(typeof(PlatformEffects.EntryClear), nameof(RoutingEffects.EntryClear))]
namespace YOURNAMESPACE.Effects.iOS
{
    [Preserve(AllMembers = true)]
    public class MaterialTextFieldClearEntry : PlatformEffect
    {
        UITextFieldViewMode old;

        protected override void OnAttached()
        {
            ConfigureControl();
        }

        protected override void OnDetached()
        {
            
            var editText = Control as UITextField;
            if (editText == null)
                return;

            editText.ClearButtonMode = old;
        }

        void ConfigureControl()
        {
            var editText = Control as UITextField;
            if (editText == null)
                return;

            old = editText.ClearButtonMode;
            editText.ClearButtonMode = UITextFieldViewMode.WhileEditing;
        }
    }
}
```
You just need to iterate over the container and find the UITextField. Since I don't own a Mac and particularly don't have knowledgment on iOS API, I can't really do much now.

**Comment by stephenhauck** [comment]
I am getting an error ...
 var editText = Container.GetChildrenOfType<EditText>().FirstOrDefault();
'ViewGroup' does not contain a definition for 'GetChildrenOfType' and the best extension overload ....

There are several other errors in the code posted on the droid side too ...

The type or namespace name 'AViewGroup' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'AView' could not be found (are you missing a using directive or an assembly reference?)

'ViewGroup' does not contain a definition for 'GetChildrenOfType' and the best extension method overload 'MaterialViewGroupExtensions.GetChildrenOfType<EditText>(AViewGroup)' requires a receiver of type 'AViewGroup'

'ViewGroup' does not contain a definition for 'GetChildrenOfType' and the best extension method overload 'MaterialViewGroupExtensions.GetChildrenOfType<EditText>(AViewGroup)' requires a receiver of type 'AViewGroup'

The type or namespace name 'AView' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'AViewGroup' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'AViewGroup' could not be found (are you missing a using directive or an assembly reference?)

**Comment by fabcall** [comment]
@stephenhauck 
Ouch, my mistake. My GetChildrenOfType function is actually in a separated file, so I forgot to copy its namespace definitions. I edited the original post. Now it should works fine. Anyways, I can send you a zip file if needed.

**Comment by stephenhauck** [comment]
I got it showing and it works but it shows all the time and is grayed out but clears when you click it ...

**Comment by fabcall** [comment]
You can change the icon color with the SetColorFilter function:

clearIcon.SetColorFilter(new PorterDuffColorFilter(Android.Graphics.Color.ParseColor(YOUR_HEX_COLOR_HERE), PorterDuff.Mode.SrcIn));

Since I'm using a slightly opaque white color (#4DFFFFFF), it does gets a little grayed. Regarding it showing all the time, I guess we can add a textchanged event listener, which would add or remove the clear icon depending on text input. I'll try something and come back in a few minutes.

**Comment by stephenhauck** [comment]
this post seems to work although I am testing 
https://stackoverflow.com/questions/47138160/xamarin-forms-add-clear-entry

**Comment by fabcall** [comment]
Perfect! This is exactly what I was thinking about. It should work fine, even thought I didn't tested yet. Anyways, I guess sooner rather than later @contrix09 will give us LeadingIcon/TrailingIcon and corresponding LeadingIconCommand/TrailingIconCommand bindable properties.

**Comment by stephenhauck** [comment]
Works on Android but in this code on iOS, Control is always null
void ConfigureControl()
        {
            var editText = Control as UITextField;

**Comment by stephenhauck** [comment]
bump ... anyone ????

**Comment by stephenhauck** [comment]
did it the same way Droid does 

 UITextFieldViewMode old;

        protected override void OnAttached()
        {
            ConfigureControl();
            
        }


        protected override void OnDetached()
        {

            var editText = Control as UITextField;
            if (editText == null)
                return;

            editText.ClearButtonMode = old;
        }

        void ConfigureControl()
        {
            
            var textField = Container.GetChildrenOfType<UITextField>().FirstOrDefault();

            if (textField == null)
                return;

            old = textField.ClearButtonMode;
            textField.ClearButtonMode = UITextFieldViewMode.WhileEditing;
        }
    }

    internal static class MaterialViewGroupExtensions
    {
        internal static IEnumerable<T> GetChildrenOfType<T>(this UIView self) where T : UIView
        {
            for (var i = 0; i < self.Subviews.Count(); i++)
            {
                UIView child = self.Subviews[i];
                var typedChild = child as T;
                if (typedChild != null)
                    yield return typedChild;

                if (child is UIView)
                {
                    IEnumerable<T> myChildren = (child as UIView).GetChildrenOfType<T>();
                    foreach (T nextChild in myChildren)
                        yield return nextChild;
                }
            }
        }

**Comment by OdetteP** [comment]
If you use MaterialTextField I have a clear entry without a cancel button. If this is still an issue please explain what you mean and add a sample code to the github repro and I will have a look. Thanks!
