### ISSUE TITLE
MaterialTextField show Placehoder when I Biding Text with object have value

### ISSUE THREAD

**Issue by tienhoangt** [Baseflow/XF-Material-Library#125]
**Describe the bug**
Show placehoder although have text

**Expected behavior**
I using MaterialTextField to input and edit text. I biding it with property of MyObject. But when Page loaded, MaterialTextField have already show placehoder although its Text property have value
![err](https://user-images.githubusercontent.com/39162026/54672486-c2c65c00-4b2a-11e9-8ce2-33c439d9f0e4.JPG)

**Comment by KyMback** [comment]
Yeah, i have the same issue. @tienhoangt did you find a solution or workaround?

**Comment by tienhoangt** [comment]
No, i haven't found solution for this issue

**Comment by OdetteP** [comment]
Did you solve this issue?
