### ISSUE TITLE
Add Image with Loading Dialog

### ISSUE THREAD

**Issue by breakcoding** [Baseflow/XF-Material-Library#126]
I'm thought is a great value for the project get this feature, I don't know if is hard to do it

When the Loading Dialog is show, you can define text, but with an Image you can describe more with words. So well if not is possible with the Loading Dialog maybe with a Dialog where you can define the GIF or PNG or a Lottie.

Well, is my suggest you know if you add this for your library

**Comment by thiagoparabas** [comment]
Great idea.

**Comment by OdetteP** [comment]
The feature is added to the library and you can now insert your own Lottie animation in Loading Dialog
