### ISSUE TITLE
On iOS MaterialCard doesn't show properly when has isvisible="false" elements inside

### ISSUE THREAD

**Issue by Jululu** [Baseflow/XF-Material-Library#127]
Sorry for my bad english, I tried to explain the best I can do it.

**Describe the bug**
On iOS, MaterialCard doesn't show properly when has isvisible="false" elements inside. In the first "charge" of the view shows irregular height for the cards.

**To Reproduce**
1. Create ListView with MaterialCards
2. Set some random labels with property "isVisible" with binding parameter in the ViewModel
3. Some of these binding parameters in false state

**Expected behavior**
show entire card with isvisible labels inside.

**Screenshots**
![IMG_0001](https://user-images.githubusercontent.com/8309379/54751309-d8935a00-4bda-11e9-93f5-ebb095b4e055.PNG)
![IMG_0003](https://user-images.githubusercontent.com/8309379/54751310-d92bf080-4bda-11e9-8072-cf39cbfe51a1.PNG)

**Smartphone (please complete the following information):**
 - Device:  iPhone6s Plus
 - OS: iOS 12.1.4
 - Version Nuget XF.Material 1.4.1

**Comment by OdetteP** [comment]
Did you solve this issue?
