### ISSUE TITLE
Is MaterialTextField InputType Choice have property SelectedIndex/SelectedItem?

### ISSUE THREAD

**Issue by tienhoangt** [Baseflow/XF-Material-Library#131]
Hi, 
Does MaterialTextField InputType Choice have property SelectedIndex/SelectedItem?
I try another solution like set text property to one string text (Choices is List of string) but when i click it, the field have that text I have already set not focus or selected. Can you add this property or something like that?
Thank for your library

**Comment by stephenhauck** [comment]
This would be excellent to have :)

**Comment by ronakshethia** [comment]
any progress on this ?

**Comment by ronakshethia** [comment]
@contrix09  please could you implement this feature ?
