### ISSUE TITLE
MaterialButton binding text and style problem

### ISSUE THREAD

**Issue by ty3ukcom** [Baseflow/XF-Material-Library#140]
on iOS not working binding of text, and problem with style when ChangeCanExecute changing.

there three screens showing difference in Android and in iOS.
1) [on start](https://github.com/ty3ukcom/XFTest/blob/master/XFTest/XFTest/Screens/1.png)
2) [after write pressed](https://github.com/ty3ukcom/XFTest/blob/master/XFTest/XFTest/Screens/2.png)
3) [after stop pressed](https://github.com/ty3ukcom/XFTest/blob/master/XFTest/XFTest/Screens/3.png)
As you see, on Android all works perfectly. But on iOS, normaly works only original buttons. Seems, with style, problem with textColor (enabled|disabled)+ it not changing when ChangeCanExecute changing. And, as you see, totally not working text binding.

source project for testing: [https://github.com/ty3ukcom/XFTest.git](https://github.com/ty3ukcom/XFTest.git)

**Comment by LewisHalliday** [comment]
Was there ever a solution to this issue?

**Comment by andy200486** [comment]
I'm facing the same problem, any solution would be appreciated

**Comment by Deepfreezed** [comment]
Having the same issue

**Comment by OdetteP** [comment]
Did the update fix this issue?
