### ISSUE TITLE
MaterialTextField keyboard open makes button non functional

### ISSUE THREAD

**Issue by MaxHampton** [Baseflow/XF-Material-Library#146]
**Describe the bug**
I have a login screen in my app that consists of two MaterialTextFields and one MaterialButton. If a user enters values into the username and password fields, the button is enabled to attempt log in. If the user taps the sign in button with the keyboard open still, the keyboard closes, but the bound ICommand on the button does not execute. If the user swipes the sign in button with the keyboard open, the bound ICommand does execute. I imagine that because a swipe gesture works, but a tap gesture does not work, a control has a tap gesture recognizer that is interfering with the button tap.

**To Reproduce**
- Create a page with a MaterialTextField and a MaterialButton with a bound command
- Focus the MaterialTextField so the keyboard is open
- Try to invoke the bound command by pressing the button with the keyboard open
- The keyboard will close, and the command will not execute

**Expected behavior**
The bound command on the button is executed when it is tapped, regardless of whether the MaterialTextField is focused, and whether the keyboard is open.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OdetteP** [comment]
Did you solve this issue?

**Comment by MaxHampton** [comment]
@OdetteP In looking into this issue, I believe this was an issue within Xamarin Forms, not with this library. When the keyboard is open and the user pressed down on a button, the keyboard would close. Because the button moved, the iOS event responsible for signaling the XamarinForms Click was not firing. 

To get around this we added a custom effect to that button so that when UIButton.TouchDragExit fires we fire ((IButtonController)Element).SendClicked();
