### ISSUE TITLE
SelectChoiceAsync Crashs on Android 5

### ISSUE THREAD

**Issue by JulianoFL** [Baseflow/XF-Material-Library#148]
Hello.
I'm getting an application crash when using _SelectChoiceAsync_ or _InputAsync_ when running on Android 5. On Android 6, 8 and 9 is running fine.

To reproduce, call one of the above methods. I've attached two log files. One of my application, and another from a recently created app. Both of the test are using this call:

`await MaterialDialog.Instance.SelectChoiceAsync("Selecione o cartão desejado", new string[] { "1", "2" });
`
**Smartphone (please complete the following information):**
Android 5.0 (simulator and device)
XF Material 1.4.1.3

[ErrorMyApplicaiton.txt](https://github.com/contrix09/XF-Material-Library/files/3170229/ErrorMyApplicaiton.txt)
[ErrorTestApplicaiton.txt](https://github.com/contrix09/XF-Material-Library/files/3170230/ErrorTestApplicaiton.txt)

**Comment by JArmandoCl** [comment]
Same problem here :s what can i do?
