### ISSUE TITLE
LeadingIcon not showing

### ISSUE THREAD

**Issue by PaulITD** [Baseflow/XF-Material-Library#152]
**Describe the bug**
When a leading icon is added to material text field, a space is inserted rather than an icon.

**To Reproduce**
1. Create a material text field in XAML
2. Add LeadingIcon property pointing to a png in Resources/Drawable or Resources (iOS)

**Expected behavior**
Image shows

**Smartphone (please complete the following information):**
 - Device: Emulator (Oreo, Pie), Simulator (iOS 12.2)
 - Version 1.4.1.3

**Comment by pedroreglero** [comment]
Same happens to me, any update?

**Comment by OdetteP** [comment]
In my reproduction it shows the icon in iOS and Android
